### ISSUE TITLE
webview can not run in goroutine

### ISSUE THREAD

**Issue by levinit** [phrozen/webview-systray-example#1]
Hi, thx your demo, I find that app will be crash while click "show" in the systray menu , it seems that webview.New(true) can not run in goroutine. 

https://github.com/webview/webview/issues/650

**Comment by phrozen** [comment]
What OS are you using? I can run in fine in Windows 10 x64 (latest), but with weird behaviour, sometimes it works perfectly, logs show webview being created and destroyed, but after a few attempts Webview will just appear minimized with no way of showing.

I have asked for a `webview.Show()` alternative so I can only show or hide the webview, but doesn't seem likely. Safe to say in does not crash the app for me, but the system webview behaviour is onconsistent to say the least. I will try to find an alternative  if both Webview and Systray have to work on the main thread.

**Comment by phrozen** [comment]
![image](https://user-images.githubusercontent.com/213238/154871900-80d965f3-7af7-45ae-b027-bdf4c9f44de3.png)

Upgraded to latest webview both Go package and dlls and it seems to be working better! I can open and close consistently! Try in your OS please.

Go-Webview: github.com/webview/webview v0.0.0-20220220170350-11de055adec5
Dlls: https://github.com/webview/webview/tree/master/dll/x64
Go 1.17.6 amd64 Windows

**Comment by phrozen** [comment]
Updated master with `go 1.17` in `go.mod` and an extra line of code in main calling `runtime.LockOSThread()` see if that fixes it for you.

https://pkg.go.dev/runtime#LockOSThread

**Comment by levinit** [comment]
I pull your newest code and try it again, 

os is macos 12.2.1
go 1.17

>fatal error: unexpected signal during runtime execution
>[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7ff80573ece4]
>
>runtime stack:
>runtime.throw({0x42f1574, 0x7ff8058ba2c5})
>	/usr/local/Cellar/go/1.17.6/libexec/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
>	/usr/local/Cellar/go/1.17.6/libexec/src/runtime/signal_unix.go:719 +0x396
>goroutine 20 [syscall, locked to thread]:
runtime.cgocall(0x42615c0, 0xc000053f20)
	/usr/local/Cellar/go/1.17.6/libexec/src/runtime/cgocall.go:156 +0x5c fp=0xc000053ef8 sp=0xc000053ec0 pc=0x4006fdc

---
thx.
maybe it can not work on my os, I will try it on windows 10 later.

**Comment by levinit** [comment]
yes, it works well in win10.

**Comment by phrozen** [comment]
I will pull tomorrow on my Mac and test a solution, will keep you posted.

**Comment by gestrada-kr** [comment]
Can confirm on OSX Catalina 10.15.7, I guess it has to do with the native OSX webview implementation. I made it work that way, but you can probably try to reverse it? Run systray in thread and webview on main, but IIRC systray does need main thread too. Sorry I couldn't be more helpful, its odd that behaviour is platform dependant, but so is webview.

**Comment by levinit** [comment]
thanks
webview proj is 
I have to split my program into 2 programs （systray and weview）, and execute each other by os/exec, although it is not very elegant.😅

**Comment by phrozen** [comment]
> I have to split my program into 2 programs （systray and weview）, and execute each other by os/exec, although it is not very elegant.😅

It gets the job done ☺️ what I would suggest is use the example in the repo to keep the server/api running with systray (and maybe add more options to the context menu).

And have a very simple project that uses embed and WebView on your public files folder. I can see myself using that... Aside from the dual ports and stuff... It works I guess.
